version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www

  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
    volumes:
      - ./:/var/www
      - ./tmp/mysqld:/var/run/mysqld

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=minecraft-map
    ports:
      - 13306:3306
